// public/data.js
// Game data for Truth or Dare — Funny & Risky (English + Arabic)
// Includes helper to return a seeded-shuffled list so the client can pull non-repeating prompts per session.

window.GameData = (function(){
  const categories = ['funny','risky'];
  const languages = ['en','ar'];

  // ---------- User-provided lists (treated as "dare"-style prompts) ----------
  const en_user_dares = [
    "Pretend to be a cat for 2 minutes.",
    "Talk in a British accent for the next 5 turns.",
    "Give someone a compliment with a serious face.",
    "Sing your favorite cartoon theme song.",
    "Do 10 jumping jacks and end with a superhero pose.",
    "Speak only in questions for the next round.",
    "Act like a robot until your next turn.",
    "Tell a joke and don’t laugh.",
    "Convince someone the floor is lava.",
    "Say 'pickle' after everything you say until your next mission.",
    "Mimic someone in the room for 1 minute.",
    "Draw a moustache on your face with a pen.",
    "Do your best evil villain laugh.",
    "Recite the alphabet backward.",
    "Balance a book on your head for 30 seconds.",
    "Act like you're stuck in slow motion.",
    "Dance without music for 30 seconds.",
    "Pretend your hand is a phone and make a call.",
    "Name 5 types of cheese in 10 seconds.",
    "Walk like a crab across the room.",
    "Try to lick your elbow.",
    "Spell your name using your body.",
    "Yell a random word dramatically.",
    "Say something nice about every person here.",
    "Make a scary face and hold it for 10 seconds.",
    "Act like a grandparent telling a story.",
    "Imitate your favorite animal.",
    "Tell a silly lie with confidence.",
    "Use your shoe as a telephone.",
    "Invent a handshake with someone.",
    "Do a runway walk.",
    "Pretend you're invisible for 1 minute.",
    "Do 5 squats while making a cow sound.",
    "Say 'I'm a banana' three times seriously.",
    "Describe your last dream dramatically.",
    "Say the alphabet skipping every other letter.",
    "Speak like a news reporter.",
    "Act like you just won an Oscar.",
    "Recite a tongue twister three times.",
    "Draw something with your eyes closed.",
    "Tell everyone your hidden talent.",
    "Whisper everything you say for the next 2 rounds.",
    "Walk like you're on the moon.",
    "Pretend to cook a meal and describe it.",
    "Make an animal sound and let people guess it.",
    "Say 3 facts about yourself — 1 must be a lie.",
    "Create a new word and define it.",
    "Pretend your hands are stuck together.",
    "Act like you're swimming in jelly.",
    "Do a dramatic reading of a random sentence.",
    "Spell 'banana' backward without writing it down.",
    "Say your favorite food like it’s a secret code.",
    "Pretend to be a pirate for 1 minute.",
    "Sing a song but replace every word with 'meow'.",
    "Act like you’re selling a random object in the room.",
    "Say everything in rhyme for the next round.",
    "Pretend to be a chef hosting a cooking show.",
    "Make up a superhero and describe their powers.",
    "Walk like you’re wearing giant clown shoes.",
    "Talk like you’re underwater for 30 seconds.",
    "Pretend to be a time traveler from the future.",
    "Do a dramatic slow-motion fight scene.",
    "Say 'bloop' after every sentence for 2 minutes.",
    "Act like you’re a detective solving a mystery.",
    "Pretend to be a puppy excited to see someone.",
    "Make a face like you just ate a lemon.",
    "Sing the alphabet song in a heavy metal style.",
    "Pretend you’re a game show host for 1 minute.",
    "Talk like you’re reading a bedtime story.",
    "Act like you’re stuck in a windstorm.",
    "Say 5 words that start with 'Z' in 10 seconds.",
    "Pretend to be a ninja sneaking across the room.",
    "Do a victory dance like you just scored a goal.",
    "Talk like you’re a radio DJ for 1 minute.",
    "Pretend you’re a statue for 30 seconds.",
    "Make up a jingle for a random object.",
    "Act like you’re in a silent movie.",
    "Say your name like you’re announcing a wrestler.",
    "Pretend to be a bird learning to fly.",
    "Do 3 cartwheels or roll across the floor.",
    "Talk like you’re a GPS giving directions.",
    "Pretend you’re a wizard casting a spell.",
    "Sing a song in reverse order.",
    "Act like you’re a catwalk model with attitude.",
    "Say 'oops' after every step you take.",
    "Pretend you’re a scientist making a discovery.",
    "Do a dance like you’re a broken robot.",
    "Talk like you’re in a cheesy rom-com.",
    "Pretend you’re a fish out of water.",
    "Say 3 things you’d bring to a desert island.",
    "Act like you’re a superhero flying through the sky.",
    "Pretend to be a grumpy old turtle.",
    "Make a sound effect for every move you make.",
    "Talk like you’re hosting a talk show.",
    "Pretend you’re a ghost haunting the room.",
    "Do a dramatic hair flip every 10 seconds.",
    "Act like you’re a penguin sliding on ice.",
    "Say everything twice for the next round.",
    "Pretend you’re a pop star at a concert.",
    "Make up a story about a random object.",
    "Act like you’re walking on hot coals.",
    "Pretend you’re a spy on a secret mission.",
    "Do a dance like you’re in a music video.",
    "Talk like you’re a villain plotting a plan.",
    "Pretend you’re a dog chasing its tail.",
    "Say 5 fruits in a dramatic voice.",
    "Act like you’re in a slow-motion race.",
    "Pretend you’re a baker kneading dough.",
    "Talk like you’re a pirate captain.",
    "Do a silly walk across the room.",
    "Pretend you’re a mime stuck in a box.",
    "Say 'yawn' after every sentence.",
    "Act like you’re a superhero with a cape.",
    "Pretend you’re a frog hopping around.",
    "Talk like you’re in a sci-fi movie.",
    "Do a cheerleader routine for 30 seconds.",
    "Pretend you’re a cowboy riding a horse.",
    "Say everything like you’re out of breath.",
    "Act like you’re a magician doing a trick.",
    "Pretend you’re a squirrel hiding nuts.",
    "Talk like you’re a motivational speaker.",
    "Do a dance like you’re at a wedding.",
    "Pretend you’re a cat stretching lazily.",
    "Say 3 animals in a whisper.",
    "Act like you’re a knight fighting a dragon.",
    "Pretend you’re a bubble floating around.",
    "Talk like you’re a game character.",
    "Do a dramatic pose every 10 seconds.",
    "Pretend you’re a chef tasting your dish.",
    "Say everything like it’s a question?",
    "Act like you’re a robot powering down.",
    "Pretend you’re a bird building a nest.",
    "Talk like you’re in a horror movie.",
    "Do a dance like you’re a flamingo.",
    "Pretend you’re a surfer riding a wave.",
    "Say 5 colors in a funny voice.",
    "Act like you’re a cat chasing a laser.",
    "Pretend you’re a superhero saving the day.",
    "Talk like you’re a stand-up comedian.",
    "Do a slow-motion victory cheer.",
    "Pretend you’re a dinosaur stomping around.",
    "Say everything with a fake cough.",
    "Act like you’re a spy dodging lasers.",
    "Pretend you’re a fish swimming upstream.",
    "Talk like you’re a cartoon villain.",
    "Do a dance like you’re in a disco.",
    "Pretend you’re a turtle pulling into your shell.",
    "Say 3 vegetables in a robot voice.",
    "Act like you’re a pirate digging for treasure.",
    "Pretend you’re a balloon losing air.",
    "Talk like you’re a sports commentator.",
    "Do a dramatic fall and recovery.",
    "Pretend you’re a cat grooming itself.",
    "Say everything like you’re freezing.",
    "Act like you’re a ninja throwing stars.",
    "Pretend you’re a cloud floating by.",
    "Talk like you’re in a soap opera.",
    "Do a dance like you’re a peacock.",
    "Pretend you’re a racecar driver.",
    "Say 5 cities in a singing voice.",
    "Act like you’re a dog digging a hole.",
    "Pretend you’re a superhero posing for photos.",
    "Talk like you’re a poet reciting.",
    "Do a slow-motion dance move.",
    "Pretend you’re a lion roaring proudly.",
    "Say everything with a hiccup.",
    "Act like you’re a spy decoding a message.",
    "Pretend you’re a jellyfish floating.",
    "Talk like you’re a game show contestant.",
    "Do a dance like you’re a robot cowboy.",
    "Pretend you’re a penguin waddling.",
    "Say 3 desserts in a dramatic voice.",
    "Act like you’re a pirate steering a ship.",
    "Pretend you’re a kite flying high.",
    "Talk like you’re a movie trailer voice.",
    "Do a dramatic spin and pose.",
    "Pretend you’re a cat pouncing on a toy.",
    "Say everything like you’re sleepy.",
    "Act like you’re a knight on a quest.",
    "Pretend you’re a bubble popping.",
    "Talk like you’re a time traveler.",
    "Do a dance like you’re a ballerina.",
    "Pretend you’re a shark circling prey.",
    "Say 5 drinks in a pirate voice.",
    "Act like you’re a dog wagging its tail.",
    "Pretend you’re a superhero landing.",
    "Talk like you’re a radio announcer.",
    "Do a slow-motion high-five.",
    "Pretend you’re a bear waking up.",
    "Say everything with a sneeze.",
    "Act like you’re a ninja hiding.",
    "Pretend you’re a wave crashing.",
    "Talk like you’re a detective.",
    "Do a dance like you’re a pop star.",
    "Pretend you’re a turtle racing.",
    "Say 3 instruments in a whisper.",
    "Act like you’re a pirate finding treasure.",
    "Pretend you’re a firework exploding.",
    "Talk like you’re a chef describing a dish.",
    "Do a dramatic jump and land.",
    "Pretend you’re a cat playing with yarn.",
    "Say everything like you’re excited.",
    "Act like you’re a knight slaying a beast.",
    "Pretend you’re a snowflake falling.",
    "Talk like you’re a superhero.",
    "Do a dance like you’re a hip-hop star.",
    "Pretend you’re a dolphin leaping.",
    "Say 5 sports in a funny voice.",
    "Act like you’re a dog catching a ball.",
    "Pretend you’re a superhero team leader.",
    "Talk like you’re a news anchor.",
    "Do a slow-motion cartwheel.",
    "Pretend you’re a bear fishing.",
    "Say everything with a giggle.",
    "Act like you’re a spy sneaking.",
    "Pretend you’re a comet zooming.",
    "Talk like you’re a cartoon hero.",
    "Do a dance like you’re a salsa star.",
    "Pretend you’re a penguin diving.",
    "Say 3 flowers in a robot voice.",
    "Act like you’re a pirate celebrating.",
    "Pretend you’re a rocket launching.",
    "Talk like you’re a game narrator.",
    "Do a dramatic bow and exit.",
    "Pretend you’re a cat napping.",
    "Say everything like you’re nervous.",
    "Act like you’re a knight guarding.",
    "Pretend you’re a leaf blowing away.",
    "Talk like you’re a movie star.",
    "Do a dance like you’re a tap dancer.",
    "Pretend you’re a whale singing.",
    "Say 5 shapes in a dramatic voice.",
    "Act like you’re a dog chasing a squirrel.",
    "Pretend you’re a superhero training.",
    "Talk like you’re a storyteller.",
    "Do a slow-motion wave to the crowd.",
    "Pretend you’re a bear hugging a tree.",
    "Say everything with a whistle.",
    "Act like you’re a spy escaping.",
    "Pretend you’re a star twinkling.",
    "Talk like you’re a game master.",
    "Do a dance like you’re a breakdancer.",
    "Pretend you’re a seal balancing a ball.",
    "Say 3 planets in a singing voice.",
    "Act like you’re a pirate dancing.",
    "Pretend you’re a plane taking off.",
    "Talk like you’re a chef on TV.",
    "Do a dramatic hair toss.",
    "Pretend you’re a cat sneaking.",
    "Say everything like you’re confused.",
    "Act like you’re a knight dueling.",
    "Pretend you’re a raindrop falling.",
    "Talk like you’re a comedian.",
    "Do a dance like you’re a jazz star."
  ];

  const ar_user_dares = [
    "اتكلم بصوت خافت لمدة دقيقتين.",
    "قل نكتة بدون ما تضحك.",
    "اعمل نفسك دكتور نفسي واسأل حد عن مشاكله.",
    "قول كلمة 'بطيخ' بعد كل جملة.",
    "قلد شخصية كرتونية.",
    "امشي في الغرفة كأنك نجم سينما.",
    "ارقص على موسيقى خيالية.",
    "اعمل صوت قطة كل ما حد يكلمك.",
    "قول جملة بس لازم تستخدم يدك في شرحها.",
    "اتكلم وكأنك مذيع نشرة الأخبار.",
    "قلد أحد أصدقاءك لمدة دقيقة.",
    "خلي الكل يسأل سؤال عنك ويجاوب عليه.",
    "ارسم نفسك وانت مغمض عينيك.",
    "امشي كأنك على القمر.",
    "استخدم شيء عشوائي كأنه ميكروفون.",
    "احكي عن يومك وكأنه فيلم أكشن.",
    "اعمل تعبير وجه يخض كل اللي حواليك.",
    "قول اسم أكلة بس بصوت حزين.",
    "قول نكتة كأنها سر خطير.",
    "اعمل نفسك روبوت لمدة دقيقة.",
    "قول ٣ حاجات عن نفسك وواحدة منهم كذب.",
    "اختر شخص واعترف له باعتراف وهمي.",
    "اختر أغنية واغنيها بصوت عالي.",
    "اتكلم بالإنجليزي بس بلهجة عربية.",
    "قول جملة فيها خمس كلمات بس كلها تبدأ بنفس الحرف.",
    "تقلد قرصان لمدة دقيقة.",
    "غني أغنية بس كل كلمة بدالها 'مياو'.",
    "اعمل نفسك بتبيع حاجة عشوائية في الأوضة.",
    "قول كل حاجة على شكل قافية في الدور الجاي.",
    "تقلد شيف بيعمل برنامج طبخ.",
    "اخترع بطل خارق ووصف قواه.",
    "امشي كأنك لابس جزمة مهرج كبيرة.",
    "اتكلم كأنك تحت المية لمدة ٣٠ ثانية.",
    "اعمل نفسك مسافر عبر الزمن من المستقبل.",
    "اعمل مشهد قتال بطيء درامي.",
    "قول 'بلووب' بعد كل جملة لمدة دقيقتين.",
    "تقلد محقق بيحل لغز.",
    "اعمل نفسك جرو فرحان بشوفت حد.",
    "اعمل وشك كأنك أكلت ليمونة.",
    "غني أغنية الأبجدية بأسلوب ميتال.",
    "تقلد مقدم برنامج مسابقات لمدة دقيقة.",
    "اتكلم كأنك بتقرأ قصة قبل النوم.",
    "اعمل نفسك في عاصفة هواء قوية.",
    "قول ٥ كلمات تبدأ بحرف 'ز' في ١٠ ثواني.",
    "تقلد نينجا بيتسلل عبر الأوضة.",
    "اعمل رقصة نصر كأنك سجلت جول.",
    "اتكلم كأنك دي جي راديو لمدة دقيقة.",
    "تجمّد كأنك تمثال لمدة ٣٠ ثانية.",
    "اخترع أغنية إعلان لحاجة عشوائية.",
    "اعمل نفسك في فيلم صامت.",
    "قول اسمك كأنك بتعرف بمصارع.",
    "تقلد طير بيتعلم يطير.",
    "اعمل ٣ شقلبات أو تدحرج ع الأرض.",
    "اتكلم كأنك GPS بيدي تعليمات.",
    "تقلد ساحر بيعمل تعويذة.",
    "غني أغنية بالعكس.",
    "امشي كأنك عارضة أزياء بغرور.",
    "قول 'أووبس' بعد كل خطوة تمشيها.",
    "تقلد عالم بيكتشف حاجة جديدة.",
    "ارقص كأنك روبوت عطلان.",
    "اتكلم كأنك في فيلم رومانسي رخيص.",
    "تقلد سمكة برا المية.",
    "قول ٣ حاجات هتاخدهم جزيرة صحراوية.",
    "تقلد بطل خارق بيطير في السما.",
    "اعمل نفسك سلحفاة عجوزة نكدية.",
    "اعمل صوت مع كل حركة تعملها.",
    "تقلد مقدم برنامج توك شو.",
    "اعمل نفسك شبح بيخوف الأوضة.",
    "اعمل حركة شعر درامية كل ١٠ ثواني.",
    "تقلد بطريق بيزلق ع الجليد.",
    "قول كل حاجة مرتين في الدور الجاي.",
    "تقلد نجم بوب في حفلة.",
    "اخترع قصة عن حاجة عشوائية.",
    "امشي كأنك ع جمر ساخن.",
    "تقلد جاسوس في مهمة سرية.",
    "ارقص كأنك في فيديو كليب.",
    "اتكلم كأنك شرير بيخطط خطة.",
    "تقلد كلب بيجري ورا ذيله.",
    "قول ٥ فواكه بصوت درامي.",
    "تقلد سباق بطيء الحركة.",
    "تقلد خباز بيعجن عجين.",
    "اتكلم كأنك قبطان قرصان.",
    "امشي بطريقة سخيفة عبر الأوضة.",
    "تقلد مايم محبوس في صندوق.",
    "قول 'تثاؤب' بعد كل جملة.",
    "تقلد بطل خارق ببرداية.",
    "تقلد ضفدع بيقفز في الأوضة.",
    "اتكلم كأنك في فيلم خيال علمي.",
    "اعمل حركات مشجعة لمدة ٣٠ ثانية.",
    "تقلد راعي بقر بيركب حصان.",
    "قول كل حاجة كأنك لسه بتجري.",
    "تقلد ساحر بيعمل خدعة.",
    "تقلد سنجاب بيخبي مكسرات.",
    "اتكلم كأنك بتدي محاضرة تحفيزية.",
    "ارقص كأنك في فرح.",
    "تقلد قطة بتتمطى بنعاس.",
    "قول ٣ حيوانات بهمس.",
    "تقلد فارس بيقاتل تنين.",
    "تقلد فقاعة بتطفو في الهوا.",
    "اتكلم كأنك شخصية في لعبة فيديو.",
    "اعمل بوز درامي كل ١٠ ثواني.",
    "تقلد شيف بيدوق أكلته.",
    "قول كل حاجة كأنها سؤال؟",
    "تقلد روبوت بيطفي.",
    "تقلد طير بيعمل عش.",
    "اتكلم كأنك في فيلم رعب.",
    "ارقص كأنك فلامنجو.",
    "تقلد راكب أمواج ع الموجة.",
    "قول ٥ ألوان بصوت مضحك.",
    "تقلد قطة بتجري ورا ليزر.",
    "تقلد بطل خارق بينقذ العالم.",
    "اتكلم كأنك كوميديان ع المسرح.",
    "اعمل هتاف نصر بطيء.",
    "تقلد ديناصور بيدوس ع الأرض.",
    "قول كل حاجة مع سعال مزيف.",
    "تقلد جاسوس بيتفادى ليزر.",
    "تقلد سمكة بتسبح ضد التيار.",
    "اتكلم كأنك شرير كرتون.",
    "ارقص كأنك في ديسكو.",
    "تقلد سلحفاة بتخش في قوقعتها.",
    "قول ٣ خضروات بصوت روبوت.",
    "تقلد قرصان بيحفر كنز.",
    "تقلد بالون بيطلع هواه.",
    "اتكلم كأنك معلق رياضي.",
    "اعمل سقوط درامي واتعافى.",
    "تقلد قطة بتتنظف.",
    "قول كل حاجة كأنك بردت.",
    "تقلد نينجا بيرمي نجم.",
    "تقلد سحابة بتطفو في السما.",
    "اتكلم كأنك في مسلسل درامي.",
    "ارقص كأنك طاووس.",
    "تقلد سائق سيارة سباق.",
    "قول ٥ مدن بصوت غنائي.",
    "تقلد كلب بيحفر حفرة.",
    "تقلد بطل خارق بيتصور.",
    "اتكلم كأنك شاعر بيقرأ.",
    "اعمل حركة رقص بطيئة.",
    "تقلد أسد بيزأر بفخر.",
    "قول كل حاجة مع زغطة.",
    "تقلد جاسوس بيفك شفرة.",
    "تقلد هلامية بتطفو.",
    "اتكلم كأنك متسابق في برنامج.",
    "ارقص كأنك راعي بقر روبوت.",
    "تقلد بطريق بيترنح.",
    "قول ٣ حلويات بصوت درامي.",
    "تقلد قرصان بيحتفل.",
    "تقلد صاروخ بيقلع.",
    "اتكلم كأنك شيف في برنامج تلفزيون.",
    "اعمل حركة شعر درامية.",
    "تقلد قطة بتتسلل.",
    "قول كل حاجة كأنك تايه.",
    "تقلد فارس بيتبارز.",
    "تقلد قطرة مطر بتقع.",
    "اتكلم كأنك كوميديان شهير.",
    "ارقص كأنك نجم جاز.",
    "تقلد حوت بيغني.",
    "قول ٥ أشكال بصوت درامي.",
    "تقلد كلب بيجري ورا سنجاب.",
    "تقلد بطل خارق بيتدرب.",
    "اتكلم كأنك راوي قصص.",
    "اعمل موجة بطيئة للجمهور.",
    "تقلد دب بيعانق شجرة.",
    "قول كل حاجة مع صفارة.",
    "تقلد جاسوس بيهرب.",
    "تقلد نجم بيلمع.",
    "اتكلم كأنك مدير لعبة.",
    "ارقص كأنك راقص بريك دانس.",
    "تقلد فقمة بتوازن كورة.",
    "قول ٣ كواكب بصوت غنائي.",
    "تقلد قرصان بيرقص.",
    "تقلد طيارة بتقلع.",
    "اتكلم كأنك شيف بيوصف أكلة.",
    "اعمل رمية شعر درامية.",
    "تقلد قطة بتتسلل.",
    "قول كل حاجة كأنك مش فاهم.",
    "تقلد فارس بيحارب.",
    "تقلد قطرة مية بتسقط.",
    "اتكلم كأنك ممثل كوميدي."
  ];

  // ---------- Extra 50 picks (funny, non-spicy) ----------
  const extra_en = [
    "Wear sunglasses indoors for the next 3 turns.",
    "Talk only in movie quotes for 2 minutes.",
    "Make up a ridiculous law and convince others to follow it.",
    "Do your best celebrity impression (no names).",
    "Attempt to whistle and narrate it dramatically.",
    "Pretend you’re making a cooking show about toast.",
    "Introduce yourself like you’re in an epic fantasy.",
    "Speak like a pirate but only when saying your name.",
    "Call a friend and tell them you just found a treasure map.",
    "Try to juggle three imaginary objects.",
    "Give a 20-second weather report for Mars.",
    "Describe your pet if it were a superhero.",
    "Make a commercial for an invisible product.",
    "Announce your own award and accept it with dignity.",
    "Do your best slow-motion entrance to the room.",
    "Create a handshake with everyone and teach it.",
    "Show your proudest dance move in slow-mo.",
    "Speak only using animal noises for 30 seconds.",
    "Mime an emotional scene from a soap opera.",
    "Invent a weird Olympic sport and demonstrate.",
    "Announce a fake holiday and explain its traditions.",
    "Make a statue pose and hold it until someone guesses it.",
    "Act like you’re stuck in an elevator with dramatic flair.",
    "Pretend to be a weather vane and spin to directions.",
    "Give a one-line review of a random object nearby.",
    "Pretend to be a museum guide for 1 minute.",
    "Whisper a dramatic secret about a pencil.",
    "Act like your phone is an old rotary and dial it.",
    "Create a short theme song for the person on your left.",
    "Demonstrate the world's worst handshake.",
    "Pretend to be a slow-motion barber giving a haircut.",
    "Talk about your day as if you were a spy.",
    "Give an emotional acceptance speech for a sandwich.",
    "Pretend you’re on a cooking show and accidentally use socks.",
    "Do your best impression of a cartoon villain’s walk.",
    "Announce a fake product recall with seriousness.",
    "Pretend to be a plant stretching toward sunlight.",
    "Make animal-shaped shadows with your hands and narrate.",
    "Offer a dramatic toast to an inanimate object.",
    "Be a dramatic narrator for someone tying their shoe.",
    "Pretend you're a professional pillow tester.",
    "Create a 10-second dramatic trailer about toast.",
    "Describe an ordinary object as if it were magic.",
    "Perform a slow clap for someone’s invisible achievement.",
    "Announce a fake sports score with passion.",
    "Act like you forgot how to walk for 5 seconds.",
    "Give a mock weather emergency for your living room.",
    "Pretend to be a detective whose only clue is a crumb.",
    "Demonstrate the ancient art of dramatic eyebrow raising.",
    "Pretend to be a model posing with a houseplant."
  ];

  const extra_ar = [
    "البس نظارة شمسية في البيت لمدة دقيقتين.",
    "اتكلم بس بأقوال أفلام لمدة دقيقتين.",
    "اخترع قانون غريب وحاول تقنع الناس بيه.",
    "قلد شخصية مشهورة بدون ما تقول اسمها.",
    "حاول تصفر وعلق عليه بتعليق درامي.",
    "تظاهر انك بتقدم برنامج طبخ عن التوست.",
    "عرف بنفسك كأنك من فيلم فانتازي.",
    "اتكلم بلهجة قرصان بس لما تقول اسمك.",
    "اتصل بصاحب وقل له لقيت خريطة كنز.",
    "حاول تلعب توازن بثلاث حاجات وهمية.",
    "اعطي تقرير جو للمريخ لمدة ٢٠ ثانية.",
    "وصف حيوانك لو كان بطل خارق.",
    "اعمل اعلان لمنتج شفاف وغير موجود.",
    "اعلن جايزة وهمية واستلمها بوقار.",
    "ادخل الغرفة بطريقة بطيئة ومبالغ فيها.",
    "اخترع مصافحة مع الكل وورّيهم.",
    "اظهر حركة رقص بفخر وببطء.",
    "اتكلم بحركات حيوانات لمدة ٣٠ ثانية.",
    "مثل مشهد عاطفي من مسلسل.",
    "اخترع لعبة اولمبية غريبة وورّيها.",
    "اعلن عن عطلة وهمية وشرح طقوسها.",
    "اعمل بوز تمثال وخلي الناس تخمن.",
    "تظاهر محبوس في مصعد بدراما.",
    "اتصرف كأنك مؤشر ريح وتلف.",
    "اعطي تقييم لحاجة جنبك بطريقة درامية.",
    "اتظاهر انك مرشد متحف لدقيقة.",
    "همس سر درامي عن قطعة قلم.",
    "اتظاهر ان تلفونك قديم ودوّار.",
    "اكتب لحن قصير للشخص على يسارك.",
    "اعرض اسوأ مصافحة في العالم.",
    "اتظاهر انك حلاق بطيء وتعمل قصة شعر.",
    "اتكلم عن يومك كأنك جاسوس.",
    "اعطي كلمة استلام درامية لساندويتش.",
    "اتظاهر انك في برنامج طبخ وتستخدم جوارب.",
    "قلد مشية شرير كرتوني.",
    "اعلن عن سحب منتج وهمي بجدية.",
    "اتظاهر انك نبتة بتمتد للشمس.",
    "اعمل ظلال حيوانات بيدك واحكي عنها.",
    "اعمل نخب درامي لشيء غير حي.",
    "احكي قصة قصيرة وانت بتحرك وسادة.",
    "اتظاهر انك مختبر وسائد محترف.",
    "اعمل اعلان درامي للتوست لمدة ١٠ ثواني.",
    "وصف حاجة عادية كأنها سحر.",
    "صفق ببطء لشئ غير مرئي.",
    "اعلن نتيجة مباراة وهمية بحماس.",
    "اتصرف كأنك نسيت المشي لدقيقة.",
    "اعطي حالة طوارئ جوية للصالون.",
    "اتظاهر انك محقق واخر دليل فتات خبز.",
    "اعمل رفع حاجب درامي.",
    "اتظاهر انك موديل وبتمثل مع نبتة."
  ];

  // ---------- Helper: seeded shuffle (deterministic for a given seed) ----------
  function mulberry32(a) {
    return function() {
      var t = a += 0x6D2B79F5;
      t = Math.imul(t ^ t >>> 15, t | 1);
      t ^= t + Math.imul(t ^ t >>> 7, t | 61);
      return ((t ^ t >>> 14) >>> 0) / 4294967296;
    }
  }

  function seededShuffle(array, seed){
    const arr = array.slice();
    const rand = mulberry32(seed >>> 0);
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(rand() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  }

  // ---------- Build final prompts object
  // We'll treat user lists as "dare" heavy content (most items are action dares).
  // For balance, we create separate 'truth' arrays with funny questions (generated here).

  const en_funny_truth = [
    "What's the most embarrassing thing on your phone right now?",
    "Which movie makes you cry like a baby?",
    "What's the weirdest food combo you secretly love?",
    "What's the dumbest way you've injured yourself?",
    "What's a word you always misspell?",
    "Have you ever sent a message to the wrong person? What was it?",
    "What's the silliest thing you're afraid of?",
    "Which childish thing do you still do sometimes?",
    "What's the funniest nickname someone gave you?",
    "What's the last weird dream you remember?",
    "What's an outfit in your past you regret?",
    "Which song do you belt out when nobody's listening?",
    "What's the most awkward thing you've said on a date?",
    "What app do you open when you're bored?",
    "What's something you pretend to understand but don't?",
    "What's the oddest compliment you've received?",
    "What's a household item you couldn't live without?",
    "What's the funniest lie you told as a kid?",
    "What's a strange talent you wish you had?",
    "When did you last laugh so hard you cried?",
    "What's a terrible habit you can't stop?",
    "What's the worst haircut you've ever had?",
    "What's the weirdest thing you collect?",
    "What's your most common autocorrect fail?",
    "What's the silliest superstition you follow?",
    "What's a word you always mispronounce?",
    "What's your funniest family tradition?",
    "What's the strangest thing you thought as a kid?",
    "Which emoji do you overuse?",
    "What's the most ridiculous excuse you used to skip school?",
    "What's the most bizarre job you could imagine having?"
  ];

  const en_risky_truth = [
    "Have you ever asked a stranger for directions when you could've used Google?",
    "What's the most public thing you've done to get attention?",
    "Have you ever pretended to be someone else online?",
    "What's the funniest lie you've told to get out of plans?",
    "Have you ever danced in public when music wasn't playing?",
    "What's the most random thing you've texted to your contact list?",
    "Have you ever tried to impress someone and failed spectacularly?",
    "What's the boldest thing you've done on a dare?",
    "What's the most awkward conversation you've had with a stranger?",
    "Have you ever faked an accent to sound cooler?"
  ];

  const ar_funny_truth = [
    "ما أغرب شيء لقيته على هاتفك؟",
    "أي فيلم يخليك تبكي من الضحك؟",
    "ما أغرب خليط أكل بتحبه؟",
    "ما أسخف طريقة إصبت فيها بنفسك؟",
    "أي كلمة دايمًا تغلط في هجائها؟",
    "هل سألت حد واكتشفت إنك غلطان في الرقم؟ ماذا كان؟",
    "ما أبسط شيء بتخش منه في رعب؟",
    "أي عادة طفولية لسة بتعملها؟",
    "ما أطرف لقب اعطاك اياه حد؟",
    "ما آخر حلم غريب تتذكره؟"
  ];

  const ar_risky_truth = [
    "عمرك طلبت سيلفي من غريب؟",
    "ما أبسط محاولة جذب انتباه عملتها في مكان عام؟",
    "هل انتحلت شخصية على الإنترنت؟",
    "ما أغرب كذبة قلتها لتتهرب من الخروج؟",
    "هل غنيت في مكان عام بدون صوت؟",
    "ما أغرب رسالة بعثتها لمجموعة جهات الاتصال؟",
    "هل حاولت تتظاهر بلكنة عشان تبين كويس؟",
    "ما أجرأ حاجة عملتها بسبب تحدي؟",
    "أغرب محادثة مع غريب؟",
    "هل مرة قمت بتصرف محرج قدام ناس كتير؟"
  ];

  // split user dares between funny.dare and risky.dare roughly
  const en_half = Math.ceil(en_user_dares.length/2);
  const ar_half = Math.ceil(ar_user_dares.length/2);

  const prompts = {
    en: {
      funny: {
        truth: en_funny_truth,
        dare: en_user_dares.slice(0, en_half).concat(extra_en.slice(0,25))
      },
      risky: {
        truth: en_risky_truth,
        dare: en_user_dares.slice(en_half).concat(extra_en.slice(25))
      }
    },
    ar: {
      funny: {
        truth: ar_funny_truth,
        dare: ar_user_dares.slice(0, ar_half).concat(extra_ar.slice(0,25))
      },
      risky: {
        truth: ar_risky_truth,
        dare: ar_user_dares.slice(ar_half).concat(extra_ar.slice(25))
      }
    }
  };

  // Public API: return shuffled list for a given language/category/type and seed
  // Usage: const arr = window.GameData.getShuffledPrompts('en','funny','dare', 12345);
  function getShuffledPrompts(lang, category, type, seed){
    seed = seed || Date.now();
    if (!prompts[lang] || !prompts[lang][category] || !prompts[lang][category][type]) return [];
    return seededShuffle(prompts[lang][category][type], Number(seed));
  }

  return { categories, languages, prompts, getShuffledPrompts };

})();
